development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: my_platform_development
  pool: 25
  username: 
  password: 
  
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: my_platform_test
  pool: 5
  username: 
  password: 
