development:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: my_platform_development
  pool: 25
  username: YOUR SYSTEM USER
  password: 
  host: localhost
  
test:
  adapter: postgresql
  encoding: unicode
  reconnect: false
  database: my_platform_test
  pool: 5
  username: YOUR SYSTEM USER
  password: 
  host: localhost
