rvm:
  - "2.3.1"
env:
  - "RSPEC_RERUN_PATTERN=./spec/features/[a-b]*_spec.rb CI_CATEGORY=features DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/features/[c]*_spec.rb CI_CATEGORY=features DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/features/[d-e]*_spec.rb CI_CATEGORY=features DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/features/[f-m]*_spec.rb CI_CATEGORY=features DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/features/[o-z]*_spec.rb CI_CATEGORY=features DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "NO_CACHING=true RSPEC_RERUN_PATTERN=./spec/models CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/models/[a-g]* CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/models/[h-r]* CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/models/[s]* CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/models/user_[a-m]* CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/models/user_spec* CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/models/[tvwxyz]* CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
  - "RSPEC_RERUN_PATTERN=./spec/uploaders/*_spec.rb CI_CATEGORY=uploaders DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=6 RAILS_ENV=test"
cache:
  - bundler
  - yarn
sudo: false
addons:
  apt:
    packages:
      - pwgen
      - libicu-dev
services:
  - redis-server
  - elasticsearch
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install
  - cd demo_app/my_platform && rake your_platform:install:node_modules || echo 'task not found'
before_script:
  - sleep 10
  - cd demo_app/my_platform
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - mkdir -p public/uploads
  - mkdir -p tmp/cache
  - bundle exec rake db:create db:migrate
  - bundle exec rake assets:precompile 2>/dev/null
  - cd ../..
script:
  - bundle exec rake rspec-rerun:spec
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14aec2cb97b9e0f2a808
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
