rvm:
  - "2.3.1"
env:
  - "RAILS_ENV=test CI_CATEGORY=features DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=4 RSPEC_RERUN_PATTERN=./spec/features/*_spec.rb"
  - "RAILS_ENV=test CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=4 RSPEC_RERUN_PATTERN=./spec/models/[a-g]*"
  - "RAILS_ENV=test CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=4 RSPEC_RERUN_PATTERN=./spec/models/[h-p]*"
  - "RAILS_ENV=test CI_CATEGORY=models DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=4 RSPEC_RERUN_PATTERN=./spec/models/[r-z]*"
  - "RAILS_ENV=test CI_CATEGORY=uploaders DB=mysql COVERALLS_SILENT=true CI=travis RSPEC_RERUN_RETRY_COUNT=4 RSPEC_RERUN_PATTERN=./spec/uploaders/*_spec.rb"
cache: bundler
sudo: false
addons:
  apt:
    packages:
      - pwgen
      - libicu-dev
services:
  - redis-server
  - elasticsearch
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
install:
  - travis_retry bundle install
before_script:
  - sleep 10
  - cd demo_app/my_platform
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - mkdir -p public/uploads
  - mkdir -p tmp/cache
  - bundle exec rake db:create db:migrate
  - cd ../..
script:
  - bundle exec rake rspec-rerun:spec
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14aec2cb97b9e0f2a808
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
