rvm:
  - "2.3.3"
env:
  - "WORKER_ID=0  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=1  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=2  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=3  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=4  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=5  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=6  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=7  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=8  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=9  NUMBER_OF_WORKERS=10 CI_CATEGORY=features                                 RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql SELENIUM=true"
  - "WORKER_ID=0  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=1  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=2  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=3  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=4  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=5  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=6  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=7  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=8  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=9  NUMBER_OF_WORKERS=10 CI_CATEGORY=models      NO_RENEW_CACHE=true          RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=0  NUMBER_OF_WORKERS=3  CI_CATEGORY=models      NO_CACHING=true              RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=1  NUMBER_OF_WORKERS=3  CI_CATEGORY=models      NO_CACHING=true              RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=2  NUMBER_OF_WORKERS=3  CI_CATEGORY=models      NO_CACHING=true              RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
  - "WORKER_ID=0  NUMBER_OF_WORKERS=1  CI_CATEGORY=others                                   RAILS_ENV=test CI=travis COVERALLS_SILENT=true DB=mysql"
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
dist: trusty
sudo: true
addons:
  firefox: latest
  chrome: stable
  apt:
    packages:
      - pwgen
      - libicu-dev
services:
  - redis-server
  - elasticsearch
before_install:
  - travis_retry gem update --system
  - travis_retry gem install bundler
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver*.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
  - travis_retry bundle install
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
before_script:
  - sleep 10
  - cd demo_app/my_platform
  - cp config/database.travis.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - mkdir -p public/uploads
  - mkdir -p tmp/cache
  - bundle exec rake db:create db:migrate
  - rake your_platform:install:node_modules || echo 'task not found'
  - bin/rails assets:precompile
  - cd ../..
  - "export DISPLAY=:99.0" # https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
  - bundle exec ruby script/tests
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/14aec2cb97b9e0f2a808
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

